### ISSUE TITLE
Broken Blog link in README

### ISSUE THREAD

**Issue by skipcloud** [benwalks/Lets-Build-Instagram-Free-Book#1]
Just a heads up, your blog link leads to a Github 404 page.

**Comment by benwalks** [comment]
Oh thanks for that, I'll fix ASAP

**Comment by nvtaveras** [comment]
@benwalks Many thanks for sharing this. The least I could do was fix it for you at #3 :)

**Comment by benwalks** [comment]
Thanks again Nelson
